{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.16-23w14a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.16-23w14a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.16-23w14a.jar",
          "size": 982340,
          "sha512": "d21e84edacec48fc7c972704bb1dae0c5c664fc1ef931290fa24186ce575ea9acc16ff3717ac92b8b880e91dbfdab6060b216d9a11d3f95766b5aabf67b32083",
          "sha256": "1c436babd7beea7a528f7adf42d611cb4c4f1051377d7dec4786f058028b46c8",
          "sha1": "199df4120190f8f26ac00293e85184ccf3f70751",
          "md5": "8693a31d64091806f39bbd9cb37bec77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.16-23w14a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.16-23w14a.jar",
          "size": 982340,
          "sha512": "d21e84edacec48fc7c972704bb1dae0c5c664fc1ef931290fa24186ce575ea9acc16ff3717ac92b8b880e91dbfdab6060b216d9a11d3f95766b5aabf67b32083",
          "sha256": "1c436babd7beea7a528f7adf42d611cb4c4f1051377d7dec4786f058028b46c8",
          "sha1": "199df4120190f8f26ac00293e85184ccf3f70751",
          "md5": "8693a31d64091806f39bbd9cb37bec77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.16-23w14a-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.16-23w14a-sources.jar",
          "size": 142058,
          "sha512": "be78fb454a0edf8977dd03a880d15b6da22d7cd1b896a4a88b911afa638ce88803ec01bf5bbd14648ab5bf837e036d2b045adab80b7d0db4c8efb9d0af2da86c",
          "sha256": "7a57c52f5989ce4eb46afd847d4ad9eb2847514cef233d3650805c4e41a96629",
          "sha1": "290806c8aea73f8b6e2d38379c15ecb5bb99af52",
          "md5": "457348022102c578d0dc4bd9690ff69c"
        }
      ]
    }
  ]
}
