{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "nucleoplasm-api-fabric",
    "version": "1.0.0.16-23w14a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.16-23w14a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.16-23w14a.jar",
          "size": 982333,
          "sha512": "ec4b2dbb063c5cbf999d2ff309b96afec851d927126077cf199e36a2bd6b516a3b160159191b7f4d738785b9f2bf2117ef0d45ab1b6960091a58a695592c8f64",
          "sha256": "5d46b80f404837fb1d9a0991c650ebd432aaf13a546e6480b6024b17a89fa304",
          "sha1": "e4206ea3e7146eeade653088ebbce52162d097c5",
          "md5": "47ed4c3e3206f653b632eba347f8e20b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.20"
          }
        },
        {
          "group": "com.github.artbits",
          "module": "quickio",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "org.iq80.leveldb",
          "module": "leveldb-api",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.protostuff",
          "module": "protostuff-collectionschema",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.16-23w14a.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.16-23w14a.jar",
          "size": 982333,
          "sha512": "ec4b2dbb063c5cbf999d2ff309b96afec851d927126077cf199e36a2bd6b516a3b160159191b7f4d738785b9f2bf2117ef0d45ab1b6960091a58a695592c8f64",
          "sha256": "5d46b80f404837fb1d9a0991c650ebd432aaf13a546e6480b6024b17a89fa304",
          "sha1": "e4206ea3e7146eeade653088ebbce52162d097c5",
          "md5": "47ed4c3e3206f653b632eba347f8e20b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nucleoplasm-api-fabric-1.0.0.16-23w14a-sources.jar",
          "url": "nucleoplasm-api-fabric-1.0.0.16-23w14a-sources.jar",
          "size": 142058,
          "sha512": "be78fb454a0edf8977dd03a880d15b6da22d7cd1b896a4a88b911afa638ce88803ec01bf5bbd14648ab5bf837e036d2b045adab80b7d0db4c8efb9d0af2da86c",
          "sha256": "7a57c52f5989ce4eb46afd847d4ad9eb2847514cef233d3650805c4e41a96629",
          "sha1": "290806c8aea73f8b6e2d38379c15ecb5bb99af52",
          "md5": "457348022102c578d0dc4bd9690ff69c"
        }
      ]
    }
  ]
}
